import uuid
from unittest import mock

from src.services.blacklist_service import BlacklistService
from src.models.errors import NotFoundError


class FakeBlacklist:
    def __init__(self, id, email, blocked_reason, created_at):
        self.id = id
        self.email = email
        self.blocked_reason = blocked_reason
        self.created_at = created_at


class FakeRepository:
    def __init__(self):
        self.stored = {}
        self.created = None

    def create(self, data):
        fake = FakeBlacklist(
            id=data["id"],
            email=data["email"],
            blocked_reason=data["blocked_reason"],
            created_at=mock.Mock(),
        )
        fake.created_at.isoformat.return_value = "2024-01-01T00:00:00"
        self.created = data
        return fake

    def get_by_email(self, email):
        return self.stored.get(email)


def test_add_to_blacklist(monkeypatch):
    repo = FakeRepository()
    service = BlacklistService()
    service.repository = repo

    result = service.add_to_blacklist(
        email="user@example.com",
        app_uuid="123e4567-e89b-12d3-a456-426614174000",
        blocked_reason="spam",
        ip_address="10.0.0.1",
    )

    assert result["email"] == "user@example.com"
    assert "added to blacklist" in result["message"]
    assert result["created_at"] == "2024-01-01T00:00:00"
    assert repo.created["ip_address"] == "10.0.0.1"
    assert repo.created["blocked_reason"] == "spam"
    # id must be a valid uuid generated by the service
    uuid.UUID(repo.created["id"])


def test_add_to_blacklist_without_reason(monkeypatch):
    repo = FakeRepository()
    service = BlacklistService()
    service.repository = repo

    result = service.add_to_blacklist(
        email="user@example.com",
        app_uuid="123e4567-e89b-12d3-a456-426614174000",
        blocked_reason=None,
        ip_address="10.0.0.1",
    )

    assert result["email"] == "user@example.com"
    assert repo.created["blocked_reason"] is None


def test_check_blacklist_found():
    repo = FakeRepository()
    repo.stored["user@example.com"] = FakeBlacklist(
        id="abc", email="user@example.com", blocked_reason="spam", created_at=None
    )
    service = BlacklistService()
    service.repository = repo

    result = service.check_blacklist("user@example.com")
    assert result["is_blacklisted"] is True
    assert result["blocked_reason"] == "spam"


def test_check_blacklist_not_found():
    repo = FakeRepository()
    service = BlacklistService()
    service.repository = repo

    result = service.check_blacklist("unknown@example.com")
    assert result["is_blacklisted"] is False
    assert result["blocked_reason"] is None
